Web/BooksForYou.Web/Controllers/AboutController.cs
namespace BooksForYou.Web.Controllers
{
    using Microsoft.AspNetCore.Mvc;

    public class AboutController : BaseController
    {
        [HttpGet]
        public ActionResult AboutUs()
        {
            return View();
        }
    }
}

Web/BooksForYou.Web/Controllers/ContactController.cs
namespace BooksForYou.Web.Controllers
{
    using System.Threading.Tasks;

    using BooksForYou.Common;
    using BooksForYou.Services.Messaging;
    using BooksForYou.Web.ViewModels.ContactUs;
    using Microsoft.AspNetCore.Mvc;

    public class ContactController : BaseController
    {
        private readonly IEmailSender _emailSender;

        public ContactController(IEmailSender emailSender)
        {
            _emailSender = emailSender;
        }

        [HttpGet]
        public ActionResult ContactUs()
        {
            var model = new ContactUsViewModel();

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> ContactUs(ContactUsViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            await _emailSender.SendEmailAsync("cyanachkov@gmail.com", model.Name, GlobalConstants.AdminMail, model.Subject, model.Message);

            return RedirectToAction("All", "Book");
        }
    }
}

Web/BooksForYou.Web/Controllers/UserController.cs
namespace BooksForYou.Web.Controllers
{
    using System;
    using System.Linq;
    using System.Security.Claims;
    using System.Text;
    using System.Text.Encodings.Web;
    using System.Threading.Tasks;

    using BooksForYou.Common;
    using BooksForYou.Data.Models;
    using BooksForYou.Services.Data.Genres;
    using BooksForYou.Services.Data.Users;
    using BooksForYou.Services.Messaging;
    using BooksForYou.Web.ViewModels.Users;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Http;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Routing;

    public class UserController : BaseController
    {
        private readonly RoleManager<ApplicationRole> _roleManager;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly IUsersService _usersService;
        private readonly IGenresService _genresService;
        private readonly IEmailSender _emailSender;

        public UserController(
           RoleManager<ApplicationRole> roleManager,
           SignInManager<ApplicationUser> signInManager,
           IUsersService userService,
           IGenresService genresService,
           IEmailSender emailSender)
        {
            _roleManager = roleManager;
            _signInManager = signInManager;
            _usersService = userService;
            _genresService = genresService;
            _emailSender = emailSender;
        }

        [Authorize(Roles = GlobalConstants.AdministratorRoleName)]
        public async Task<IActionResult> All([FromQuery] int p = 1, [FromQuery] int s = 5)
        {
            var users = await _usersService.GetUsersAsync(p, s);

            return View(users);
        }

        [Authorize(Roles = GlobalConstants.AdministratorRoleName)]
        public async Task<IActionResult> AllUsersAuthors([FromQuery] int p = 1, [FromQuery] int s = 5)
        {
            var users = await _usersService.GetUsersAuthorsAsync(p, s);

            return View(users);
        }

        [HttpGet]
        [Authorize(Roles = GlobalConstants.AdministratorRoleName)]
        public async Task<IActionResult> Edit(string id)
        {
            var model = await _usersService.GetUserForEditAsync(id);

            return View(model);
        }

        [HttpPost]
        [Authorize(Roles = GlobalConstants.AdministratorRoleName)]
        public async Task<IActionResult> Edit(string id, UserEditViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            await _usersService.UpdateUserAsync(id, model);

            return RedirectToAction(nameof(All));
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> RequestToBecome()
        {
             var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

             if (await _usersService.ExistsById(userId) == true)
             {
                return RedirectToAction("All", "Book");
             }

             var model = new UserRequestToBecomeAuthorViewModel();
             return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> RequestToBecome(UserRequestToBecomeAuthorViewModel model)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            if (await _usersService.UserWithWebsiteExists(model.Website))
            {
                ModelState.AddModelError(nameof(model.Website), "The website already exist.");
            }

            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var html = new StringBuilder();
            html.AppendLine($"<h1>{"Request to become author!"}</h1>");
            html.AppendLine($"<h3>{"Dear Administrator,pls would you like to make me an author?"}</h3>");
            await _emailSender.SendEmailAsync("cyanachkov@gmail.com", "Books For You!", GlobalConstants.AdminMail, "Admin", html.ToString());

            return RedirectToAction("All", "Book");
        }

        [HttpGet]
        public async Task<IActionResult> BecomeAuthor()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            var model = await _usersService.GetUserBecomeAuthorAsync(userId);
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> BecomeAuthor(UserBecomesAuthorViewModel model, IFormFile file)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            if (file == null || file.Length == 0)
            {
                model.Genres = await _genresService.GetGenresToCreateAsync();
                return this.View(model);
            }

            if (!ModelState.IsValid)
            {
                model.Genres = await _genresService.GetGenresToCreateAsync();
                return View(model);
            }

            try
            {
                await _usersService.UserBecomeAuthorAsync(userId, model, file);

                return RedirectToAction("Index", "Home");
            }
            catch (Exception)
            {
                ModelState.AddModelError(string.Empty, "Something went wrong");
                return View(model);
            }
        }

        [HttpGet]
        public async Task<IActionResult> UserAuthorById(string id)
        {
            var authorModel = await _usersService.GetUserAuthorByIdAsync<UserAuthorSingleViewModel>(id);

            return View(authorModel);
        }
    }
}

Web/BooksForYou.Web/Views/Shared/_Layout.cshtml
@using BooksForYou.Common
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@this.ViewData["Title"] - @GlobalConstants.SystemName</title>

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <link rel="stylesheet" href="~/plugins/fontawesome-free/css/all.min.css">
    <link rel="stylesheet" href="~/css/adminlte.min.css">

    <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    @await this.RenderSectionAsync("Head", required: false)
</head>
<body class="hold-transition dark-mode sidebar-mini layout-fixed layout-navbar-fixed layout-footer-fixed">
    <div class="wrapper">

        
        <nav class="main-header navbar navbar-expand navbar-dark">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Contact" asp-action="ContactUs">Contact Us</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="About" asp-action="AboutUs">About Us</a>
                </li>
            </ul>

            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" data-widget="fullscreen" href="#" role="button">
                        <i class="fas fa-expand-arrows-alt"></i>
                    </a>
                </li>
            </ul>
        </nav>
        <aside class="main-sidebar sidebar-dark-primary elevation-4">
            <a href="/" class="brand-link">
                <img src="~/img/AdminLTELogo.png" alt="Book" class="brand-image img-bordered-sm elevation-3" style="opacity: .3">
                <span class="brand-text font-weight-light">@GlobalConstants.SystemName</span>
            </a>

            <div class="sidebar">
                <partial name="_LoginPartial" />
                <hr />
                <partial name="_MainMenu" />
            </div>
        </aside>

        <div class="content-wrapper">
            <div class="content-header">
                <div class="container-fluid">
                    <div class="row mb-2">
                        <div class="col-sm-6">
                        </div>
                    </div>
                </div>
                <div class="content">
                    <div class="container-fluid">
                        <partial name="_CookieConsentPartial" />
                        @this.RenderBody()
                    </div>
                </div>
            </div>
            <footer class="main-footer">
                <div class="float-right d-none d-sm-inline-block">
                    Book for Everyone!
                </div>
                <strong>Copyright &copy; @DateTime.Now.Year - @GlobalConstants.SystemName - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a></strong>
            </footer>
        </div>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js" asp-append-version="true"></script>
    <script src="~/plugins/bootstrap/js/bootstrap.bundle.min.js" asp-append-version="true"></script>
    <script src="~/js/adminlte.min.js"></script>
    <script src="~/js/site.min.js" asp-append-version="true"></script>
    <script src="~/plugins/toastr/toastr.min.js"></script>

    @await this.RenderSectionAsync("Scripts", required: false)
</body>
</html>

Web/BooksForYou.Web/Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">


    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <link rel="stylesheet" href="~/css/adminlte.min.css">
    <link rel="stylesheet" href="~/css/appValidation.css">
    <link rel="stylesheet" href="~/plugins/icheck-bootstrap/icheck-bootstrap.min.css">

</head>
<body class="hold-transition login-page">

    @RenderBody()

    <script src="~/lib/jquery/dist/jquery.min.js" asp-append-version="true"></script>
    <script src="~/js/adminlte.min.js"></script>
    <script src="~/js/site.min.js" asp-append-version="true"></script>
    <partial name="_ValidationScriptsPartial" />


    @RenderSection("Scripts", required: false)
</body>
</html>

Web/BooksForYou.Web/Views/Shared/_MainMenu.cshtml
@using BooksForYou.Common;
<nav class="mt-2">
    <ul class="nav nav-pills nav-sidebar">
        <li class="nav-item">
            <a asp-area="" asp-controller="Book" asp-action="All" class="nav-link">
                <i class="nav-icon fas fa-home"></i>
                <p>
                    Home
                </p>
            </a>
        </li>
        <li class="nav-item">
            <a asp-area="" asp-controller="Home" asp-action="Privacy" class="nav-link">
                <i class="nav-icon fas fa-wallet"></i>
                <p>
                    Privacy
                </p>
            </a>
        </li>
        @if (!User.IsInRole(GlobalConstants.AuthorRoleName) && User.Identity.IsAuthenticated)
        {
            <li class="nav-item">
                <a asp-area="" asp-controller="User" asp-action="RequestToBecome" class="nav-link">
                    <i class="nav-icon fas fa-wallet"></i>
                    <p>
                        Become author
                    </p>
                </a>
            </li>
        }
    </ul>
</nav>